# CI for Product Catalog Service

name: product-catalog-ci

on: 
    pull_request:
        branches:
        - main

permissions:
    id-token: write
    contents: write
    
jobs:

    generate-tag:
        runs-on: ubuntu-latest
    
        outputs:
          image_tag: ${{ steps.tag.outputs.image_tag }}
    
        steps:
          - name: Generate image tag
            id: tag
            run: |
              echo "image_tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
        
        - name: Build
          run: |
            cd src/product-catalog
            go mod download
            go build -o product-catalog-service main.go

        - name: unit tests
          run: |
            cd src/product-catalog
            go test ./...
    
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Setup Go 1.22
          uses: actions/setup-go@v2
          with:
           go-version: 1.22
        
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.55.2
            run: golangci-lint run
            working-directory: src/product-catalog

    docker:
      runs-on: ubuntu-latest
      needs: [build, generate-tag]
      steps:
        - name: Set date
          run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
        - name: checkout code
          uses: actions/checkout@v4

        - name: Install Docker
          uses: docker/setup-buildx-action@v1
        
        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Docker Push
          uses: docker/build-push-action@v6
          with:
            context: src/product-catalog
            file: src/product-catalog/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ needs.generate-tag.outputs.image_tag }}

    
    updatek8s:
      runs-on: ubuntu-latest
      needs: [docker, generate-tag]
      steps:
        - name: Set date
          run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
        - name: checkout code
          uses: actions/checkout@v4
          with:
            # FIX 2: Force checkout of the actual HEAD branch of the PR, not the merge preview
            ref: ${{ github.head_ref }}
            token: ${{ github.token }}
            persist-credentials: true
            
        - name: List files in workspace root
          run: ls -la
          
        - name: Update tag in kubernetes deployment manifest
          run: | 
               sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ needs.generate-tag.outputs.image_tag }}|" kubernetes/productcatalog/deploy.yaml
        
        - name: Commit and push changes
          run: |
            git config --global user.email "rasimh542@gmail.com"
            git config --global user.name "Rasim Huseynov"
            git add kubernetes/productcatalog/deploy.yaml
            git commit -m "[CI]: Update product catalog image tag"
            git push origin HEAD:main -f
            
    deploy-qa:
        runs-on: ubuntu-latest
    
        needs: [updatek8s, generate-tag]
    
        environment: qa
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v6.1.0
            with:
              audience: sts.amazonaws.com
              aws-region: eu-north-1
              role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
    
          - name: Update kubeconfig
            run: |
              aws eks update-kubeconfig \
                --region eu-north-1 \
                --name rasim-eks-cluster
    
          - name: Verify cluster connection
            run: kubectl get nodes
    
          - name: Create QA namespace if not exists
            run: |
              kubectl create namespace qa --dry-run=client -o yaml | kubectl apply -f -
    
          - name: Apply Kubernetes manifests
            run: |
              kubectl apply -f kubernetes/productcatalog/deploy.yaml -n qa
    
    
          - name: Verify deployment rollout
            run: |
              kubectl rollout status deployment/product-catalog -n qa

    oidc-test:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials connection test
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                audience: sts.amazonaws.com
                aws-region: eu-north-1
                role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
            - name: verify command output
              run: aws sts get-caller-identity
            
        
          


        
