# CI for Product Catalog Service

name: product-catalog-ci

on: 
    pull_request:
        branches:
        - main
    
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    
jobs:

    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
            
        - name: Generate and Save Tag
          run: |
            # Combines the fixed version prefix with the timestamp
            TAG="v1.0_$(date +'%Y%m%d%H%M%S')"
            echo "$TAG" > release-tag.txt
            echo "Generated Tag: $TAG"
        
        - name: Build
          run: |
            cd src/product-catalog
            go mod download
            go build -o product-catalog-service main.go

        - name: unit tests
          run: |
            cd src/product-catalog
            go test ./...

        - name: Upload Tag Artifact
          uses: actions/upload-artifact@v4
          with:
              name: release-tag
              path: release-tag.txt
              retention-days: 90
    
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Setup Go 1.22
          uses: actions/setup-go@v2
          with:
           go-version: 1.22
        
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.55.2
            run: golangci-lint run
            working-directory: src/product-catalog

    docker:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        # - name: Set date
        #   run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
        - name: checkout code
          uses: actions/checkout@v4

        - name: Download Tag Artifact
          uses: actions/download-artifact@v4
          with:
            name: release-tag # Must match the upload name exactly

        - name: Read Tag into Environment Variable
          id: get_tag
          run: |
            # Reads the file content and strips any trailing newlines
            TAG_VALUE=$(cat release-tag.txt | tr -d '\n')
            echo "IMAGE_TAG=$TAG_VALUE" >> $GITHUB_ENV

        - name: Install Docker
          uses: docker/setup-buildx-action@v3
        
        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Docker Push
          uses: docker/build-push-action@v6
          with:
            context: src/product-catalog
            file: src/product-catalog/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ env.IMAGE_TAG }}
            
    deploy-qa:
        runs-on: ubuntu-latest
    
        needs: [docker]
    
        environment: qa
    
        steps:
         # - name: Download modified deployment manifest from updatek8s
         #   uses: actions/download-artifact@v4
         #   with:
         #     name: updated-k8s-deployment-tag
         #     path: kubernetes/productcatalog/
    
         # - name: Verify manifest contains the correct generated tag
         #   run: grep "image:" kubernetes/productcatalog/deploy.yaml

        - name: checkout code
          uses: actions/checkout@v4
          with:
            # FIX 2: Force checkout of the actual HEAD branch of the PR, not the merge preview
            ref: ${{ github.head_ref }}
            token: ${{ github.token }}
            persist-credentials: true

        - name: Download Tag Artifact
          uses: actions/download-artifact@v4
          with:
            name: release-tag # Must match the upload name exactly
            
        - name: List files in workspace root
          run: ls -la
        
        - name: Read Tag into Environment Variable
          id: get_tag
          run: |
            # Reads the file content and strips any trailing newlines
            TAG_VALUE=$(cat release-tag.txt | tr -d '\n')
            echo "IMAGE_TAG=$TAG_VALUE" >> $GITHUB_ENV
            
       
        - name: Update tag in kubernetes deployment manifest and verify
          run: | 
               sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:{{TAG}}|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ env.IMAGE_TAG }}|" kubernetes/productcatalog/deploy.yaml
               grep "image:" kubernetes/productcatalog/deploy.yaml

         
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v6.1.0
          with:
             audience: sts.amazonaws.com
             aws-region: eu-north-1
             role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
             
        - name: Update kubeconfig
          run: |
              aws eks update-kubeconfig \
                --region eu-north-1 \
                --name rasim-eks-cluster
    
        - name: Verify cluster connection
          run: kubectl get nodes
    
        - name: Create QA namespace if not exists
          run: |
              kubectl create namespace qa --dry-run=client -o yaml | kubectl apply -f -
    
        - name: Apply Kubernetes manifests
          run: |
              kubectl apply -f kubernetes/productcatalog/deploy.yaml -n qa
    
    
        - name: Verify deployment rollout
          run: |
              kubectl get deployments opentelemetry-demo-productcatalogservice -n qa
              # kubectl rollout status deployment/opentelemetry-demo-productcatalogservice -n qa
              
    deploy-staging:
        runs-on: ubuntu-latest
    
        needs: [deploy-qa]
    
        environment: staging
    
        steps:
         
         - name: checkout code
           uses: actions/checkout@v4
           with:
            # FIX 2: Force checkout of the actual HEAD branch of the PR, not the merge preview
            ref: ${{ github.head_ref }}
            token: ${{ github.token }}
            persist-credentials: true

         - name: Download Tag Artifact
           uses: actions/download-artifact@v4
           with:
            name: release-tag # Must match the upload name exactly
            
         - name: List files in workspace root
           run: ls -la
        
         - name: Read Tag into Environment Variable
           id: get_tag
           run: |
            # Reads the file content and strips any trailing newlines
            TAG_VALUE=$(cat release-tag.txt | tr -d '\n')
            echo "IMAGE_TAG=$TAG_VALUE" >> $GITHUB_ENV
            
       
         - name: Update tag in kubernetes deployment manifest and verify
           run: | 
               sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:{{TAG}}|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ env.IMAGE_TAG }}|" kubernetes/productcatalog/deploy.yaml
               grep "image:" kubernetes/productcatalog/deploy.yaml
    
         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v6.1.0
           with:
              audience: sts.amazonaws.com
              aws-region: eu-north-1
              role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
    
         - name: Update kubeconfig
           run: |
              aws eks update-kubeconfig \
                --region eu-north-1 \
                --name rasim-eks-cluster
    
         - name: Verify cluster connection
           run: kubectl get nodes
    
         - name: Create staging namespace if not exists
           run: |
              kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -
    
         - name: Apply Kubernetes manifests
           run: |
              kubectl apply -f kubernetes/productcatalog/deploy.yaml -n staging
    
    
         - name: Verify deployment rollout
           run: |
              kubectl get deployments opentelemetry-demo-productcatalogservice -n staging
              # kubectl rollout status deployment/opentelemetry-demo-productcatalogservice -n staging
              
    deploy-prod:
        runs-on: ubuntu-latest
    
        needs: [deploy-staging]
    
        environment: prod
    
        steps:
        
          - name: checkout code
            uses: actions/checkout@v4
            with:
             # FIX 2: Force checkout of the actual HEAD branch of the PR, not the merge preview
             ref: ${{ github.head_ref }}
             token: ${{ github.token }}
             persist-credentials: true

          - name: Download Tag Artifact
            uses: actions/download-artifact@v4
            with:
              name: release-tag # Must match the upload name exactly
            
          - name: List files in workspace root
            run: ls -la
        
          - name: Read Tag into Environment Variable
            id: get_tag
            run: |
             # Reads the file content and strips any trailing newlines
             TAG_VALUE=$(cat release-tag.txt | tr -d '\n')
             echo "IMAGE_TAG=$TAG_VALUE" >> $GITHUB_ENV
            
       
          - name: Update tag in kubernetes deployment manifest and verify
            run: | 
               sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:{{TAG}}|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ env.IMAGE_TAG }}|" kubernetes/productcatalog/deploy.yaml
               grep "image:" kubernetes/productcatalog/deploy.yaml
              
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v6.1.0
            with:
              audience: sts.amazonaws.com
              aws-region: eu-north-1
              role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
    
          - name: Update kubeconfig
            run: |
              aws eks update-kubeconfig \
                --region eu-north-1 \
                --name rasim-eks-cluster
    
          - name: Verify cluster connection
            run: kubectl get nodes
    
          - name: Create prod namespace if not exists
            run: |
              kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -
    
          - name: Apply Kubernetes manifests
            run: |
              kubectl apply -f kubernetes/productcatalog/deploy.yaml -n prod
    
    
          - name: Verify deployment rollout
            run: |
              kubectl get deployments opentelemetry-demo-productcatalogservice -n prod
              # kubectl rollout status deployment/opentelemetry-demo-productcatalogservice -n prod

    oidc-test:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials connection test
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                audience: sts.amazonaws.com
                aws-region: eu-north-1
                role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
            - name: verify command output
              run: aws sts get-caller-identity
            
        
          


        
